# Generated by Django 5.1.1 on 2024-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=300, verbose_name='descripcion'),
        ),
    ]
